services:
  fastapi_app:
    build: .
    ports:
      - "4200:8000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: web_db
      DB_HOST: postgres_db
      DB_PORT: 5432
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web_db
    ports:
      - "5432:5432"
    volumes:
      - web_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d web_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  web_postgres_data: