services:
  fastapi_app:
    build: .
    ports:
      - "4200:8000"
    env_file:
      - .env
    environment:
      # Явно прокидываем переменные, чтобы .env загрузился корректно
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
      - TOKEN_HASH_SALT=${TOKEN_HASH_SALT}
      - YANDEX_CLIENT_ID=${YANDEX_CLIENT_ID}
      - YANDEX_CLIENT_SECRET=${YANDEX_CLIENT_SECRET}
      - YANDEX_REDIRECT_URI=${YANDEX_REDIRECT_URI}
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - lab3_pgdata:/var/lib/postgresql/data

volumes:
  lab3_pgdata:
